### ISSUE TITLE
Links for zlib and GiNaC broken because of new versions

### ISSUE THREAD

**Issue by nils-tomforde** [magv/hepware#1]
There are new versions of zlib and GiNaC and the programs are no longer available under the links for the old version used in the Makefile.
This can be fixed using the following replacements:

line 197: .../zlib-1.2.13.tar.xz" --> .../zlib-1.3.tar.xz"
line 379: .../ginac-1.8.6.tar.bz2" --> .../ginac-1.8.7.tar.bz2"

**Comment by magv** [comment]
Updated, thanks! I found a stable download url for zlib, but not for ginac, so it would need to be updated on the next release too (unless a stable url exists).
